---
title             : "What's behind option ABC?"
shorttitle        : "ABC is not DIFF"

author: 
  - name          : "Brock Rowley"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "175 Lokey Education 5262 University of Oregon"
    email         : "brockr@uoregon.edu"
  - name          : "Daniel Anderson"
    affiliation   : "1"
  - name          : "Sevrina Tindal"
    affiliation   : "1"
  - name          : "Gerald Tindal"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "University of Oregon"

authornote: |
  Behavioral Research & Teaching (BRT).

  This work was funded as part of an ongoing contract with the Oregon Department of Education.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "Item Option Analysis"
wordcount         : "X"

bibliography      : refs.bib

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
header-includes:
  - \raggedbottom
  - \setlength{\parskip}{0pt}
  - \newcommand{\GG}[1]{}
class             : "man, fleqn, noextraspace"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

# Intro

# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References


\begingroup
\setlength{\parindent}{-0.25in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
